/*********************************************************************************************
 * TYPE.H
 * 定义基本参数变量 
 * 2010-8-2
 *********************************************************************************************/

#ifndef _TYPEDEFINITON_
#define _TYPEDEFINITON_

#define  INT8U   unsigned char   
#define  INT8S            char   
#define  INT16U  unsigned short  
#define  INT16S           short  
#define  INT32U  unsigned long   
#define  INT32S           long   
#define  F32     float    
#define  F64     double	 

#define  UINT8   uint8_t 	 
#define  UINT16  uint16_t  
#define  UINT32  uint32_t  
#define  INT32   int32_t  
#define  uchar   uint8_t 
#define  ushort  uint16_t 
#define  BOOL	 INT32

//#define  u8      uint8_t 	 
//#define  u16     uint16_t  
//#define  u32     uint32_t  
//#define  s32     int32_t  
//#define  s8      uint8_t 
//#define  s16     uint16_t 

#define  BYTE    INT8U
#define  WORD    INT16U   
#define  DWORD   INT32U  

#define  TRUE     1
#define  FALSE    0

#define  ON      1u
#define  OFF     0u
#endif
